# Generated by Django 5.1.2 on 2025-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=128)),
                ('prenomsClient', models.CharField(max_length=128)),
                ('adresse', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dateAjout'],
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMenu', models.CharField(max_length=128)),
                ('composition', models.CharField(max_length=128)),
                ('descriptions', models.TextField()),
                ('categorie', models.CharField(max_length=128)),
                ('prixUnitaire', models.FloatField(null=True, verbose_name='0')),
                ('disponible', models.CharField(choices=[('O/Y', 'OUI/YES'), ('N/N', 'NON/NO')], default='O/Y')),
                ('dateAjout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dateAjout'],
            },
        ),
    ]
