# Generated by Django 5.1.3 on 2024-12-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('filiere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('pu', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('codeUE', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nbreCredit', models.IntegerField()),
                ('inscrit', models.ManyToManyField(through='firstapp.Inscription', to='firstapp.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ue'),
        ),
    ]
