# Generated by Django 5.1.2 on 2025-01-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_categorie_dateajout_produit_dateajout_produit_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-dateAjout']},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-nom']},
        ),
    ]
