# Generated by Django 4.2.18 on 2025-01-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_categorie_options_alter_produit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-dateAjout']},
        ),
    ]
