# Generated by Django 4.2.18 on 2025-01-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_produit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='firstapp.categorie', verbose_name='Catégorie du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateAjout',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=128, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixUnitaire',
            field=models.FloatField(default=0, verbose_name='Prix Unitaitaire du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Quantité du produit'),
        ),
    ]
