# Generated by Django 4.2.18 on 2025-01-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_produit_categorie_alter_produit_dateajout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prixUnitaire',
            field=models.FloatField(default=0, verbose_name='Prix unitaitaire du produit'),
        ),
    ]
