# Generated by Django 4.2.18 on 2025-01-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_produit_prixunitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
    ]
